export const dummyTransactions = [
  // XRUN (id = 1)
  {
    id: 'txn-1-1',
    assetId: '1',
    symbol: 'XRUN',
    type: 'receive',
    amount: '320',
    date: '2025.05.18 10:15',
    icon: require('./../../../assets/images/icon_xrun_white.png'),
  },
  {
    id: 'txn-1-2',
    assetId: '1',
    symbol: 'XRUN',
    type: 'send',
    amount: '150',
    date: '2025.05.17 22:03',
    icon: require('./../../../assets/images/icon_xrun_white.png'),
  },
  {
    id: 'txn-1-3',
    assetId: '1',
    symbol: 'XRUN',
    type: 'receive',
    amount: '80',
    date: '2025.05.16 08:45',
    icon: require('./../../../assets/images/icon_xrun_white.png'),
  },
  {
    id: 'txn-1-4',
    assetId: '1',
    symbol: 'XRUN',
    type: 'send',
    amount: '240',
    date: '2025.05.14 19:27',
    icon: require('./../../../assets/images/icon_xrun_white.png'),
  },
  {
    id: 'txn-1-5',
    assetId: '1',
    symbol: 'XRUN',
    type: 'receive',
    amount: '500',
    date: '2025.05.13 12:01',
    icon: require('./../../../assets/images/icon_xrun_white.png'),
  },

  // POLYGON (id = 2)
  {
    id: 'txn-2-1',
    assetId: '2',
    symbol: 'POL',
    type: 'receive',
    amount: '450',
    date: '2025.05.17 11:22',
    icon: require('./../../../assets/images/icon_polygon.png'),
  },
  {
    id: 'txn-2-2',
    assetId: '2',
    symbol: 'POL',
    type: 'send',
    amount: '80',
    date: '2025.05.16 14:00',
    icon: require('./../../../assets/images/icon_polygon.png'),
  },
  {
    id: 'txn-2-3',
    assetId: '2',
    symbol: 'POL',
    type: 'receive',
    amount: '200',
    date: '2025.05.15 18:45',
    icon: require('./../../../assets/images/icon_polygon.png'),
  },
  {
    id: 'txn-2-4',
    assetId: '2',
    symbol: 'POL',
    type: 'send',
    amount: '100',
    date: '2025.05.13 09:12',
    icon: require('./../../../assets/images/icon_polygon.png'),
  },
  {
    id: 'txn-2-5',
    assetId: '2',
    symbol: 'POL',
    type: 'receive',
    amount: '300',
    date: '2025.05.12 21:33',
    icon: require('./../../../assets/images/icon_polygon.png'),
  },

  // REALVERSE (id = 3)
  {
    id: 'txn-3-1',
    assetId: '3',
    symbol: 'REALVERSE',
    type: 'send',
    amount: '300000',
    date: '2025.05.16 13:11',
    icon: require('./../../../assets/images/icon_realverse.png'),
  },
  {
    id: 'txn-3-2',
    assetId: '3',
    symbol: 'REALVERSE',
    type: 'receive',
    amount: '200000',
    date: '2025.05.15 16:49',
    icon: require('./../../../assets/images/icon_realverse.png'),
  },
  {
    id: 'txn-3-3',
    assetId: '3',
    symbol: 'REALVERSE',
    type: 'send',
    amount: '100000',
    date: '2025.05.14 20:27',
    icon: require('./../../../assets/images/icon_realverse.png'),
  },
  {
    id: 'txn-3-4',
    assetId: '3',
    symbol: 'REALVERSE',
    type: 'receive',
    amount: '250000',
    date: '2025.05.13 10:42',
    icon: require('./../../../assets/images/icon_realverse.png'),
  },
  {
    id: 'txn-3-5',
    assetId: '3',
    symbol: 'REALVERSE',
    type: 'receive',
    amount: '150000',
    date: '2025.05.12 22:05',
    icon: require('./../../../assets/images/icon_realverse.png'),
  },

  // NFT #8282 (id = 4)
  {
    id: 'txn-4-1',
    assetId: '4',
    symbol: 'NFT #8282',
    type: 'receive',
    amount: '1',
    date: '2025.05.18 15:25',
    icon: require('./../../../assets/images/icon_nft_black.png'),
  },
  {
    id: 'txn-4-2',
    assetId: '4',
    symbol: 'NFT #8282',
    type: 'send',
    amount: '1',
    date: '2025.05.17 17:03',
    icon: require('./../../../assets/images/icon_nft_black.png'),
  },
  {
    id: 'txn-4-3',
    assetId: '4',
    symbol: 'NFT #8282',
    type: 'receive',
    amount: '1',
    date: '2025.05.16 20:45',
    icon: require('./../../../assets/images/icon_nft_black.png'),
  },
  {
    id: 'txn-4-4',
    assetId: '4',
    symbol: 'NFT #8282',
    type: 'receive',
    amount: '1',
    date: '2025.05.15 09:30',
    icon: require('./../../../assets/images/icon_nft_black.png'),
  },
  {
    id: 'txn-4-5',
    assetId: '4',
    symbol: 'NFT #8282',
    type: 'send',
    amount: '1',
    date: '2025.05.13 11:00',
    icon: require('./../../../assets/images/icon_nft_black.png'),
  },

  // NFT #8283 (id = 5)
  {
    id: 'txn-5-1',
    assetId: '5',
    symbol: 'NFT #8283',
    type: 'receive',
    amount: '1',
    date: '2025.05.18 08:00',
    icon: require('./../../../assets/images/icon_nft_black.png'),
  },
  {
    id: 'txn-5-2',
    assetId: '5',
    symbol: 'NFT #8283',
    type: 'receive',
    amount: '1',
    date: '2025.05.16 22:41',
    icon: require('./../../../assets/images/icon_nft_black.png'),
  },
  {
    id: 'txn-5-3',
    assetId: '5',
    symbol: 'NFT #8283',
    type: 'send',
    amount: '1',
    date: '2025.05.15 13:13',
    icon: require('./../../../assets/images/icon_nft_black.png'),
  },
  {
    id: 'txn-5-4',
    assetId: '5',
    symbol: 'NFT #8283',
    type: 'send',
    amount: '1',
    date: '2025.05.14 15:55',
    icon: require('./../../../assets/images/icon_nft_black.png'),
  },
  {
    id: 'txn-5-5',
    assetId: '5',
    symbol: 'NFT #8283',
    type: 'receive',
    amount: '1',
    date: '2025.05.13 21:18',
    icon: require('./../../../assets/images/icon_nft_black.png'),
  },

  // AD XRUN (id = 6)
  {
    id: 'txn-6-1',
    assetId: '6',
    symbol: 'AD XRUN',
    type: 'send',
    amount: '100',
    date: '2025.05.18 19:20',
    icon: require('./../../../assets/images/icon_ad_xrun.png'),
  },
  {
    id: 'txn-6-2',
    assetId: '6',
    symbol: 'AD XRUN',
    type: 'receive',
    amount: '200',
    date: '2025.05.17 23:10',
    icon: require('./../../../assets/images/icon_ad_xrun.png'),
  },
  {
    id: 'txn-6-3',
    assetId: '6',
    symbol: 'AD XRUN',
    type: 'send',
    amount: '50',
    date: '2025.05.16 11:45',
    icon: require('./../../../assets/images/icon_ad_xrun.png'),
  },
  {
    id: 'txn-6-4',
    assetId: '6',
    symbol: 'AD XRUN',
    type: 'receive',
    amount: '120',
    date: '2025.05.15 17:00',
    icon: require('./../../../assets/images/icon_ad_xrun.png'),
  },
  {
    id: 'txn-6-5',
    assetId: '6',
    symbol: 'AD XRUN',
    type: 'receive',
    amount: '30',
    date: '2025.05.14 09:55',
    icon: require('./../../../assets/images/icon_ad_xrun.png'),
  },
];
